# Generated by Django 3.1.7 on 2021-03-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('duties', models.TextField(max_length=1000)),
                ('requirments', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=200)),
                ('position', models.ForeignKey(models.Position, on_delete=models.CASCADE)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('employee', models.ForeignKey(models.Employee, on_delete=models.CASCADE)),
            ],
        ),
        migrations.CreateModel(
            name='Additional_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('characteristics', models.TextField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Body_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('manufacturer', models.ForeignKey(models.Manufacturer, on_delete=models.CASCADE)),
                ('body_type', models.ForeignKey(models.Body_type, on_delete=models.CASCADE)),
                ('date', models.DateField(auto_now=True)),
                ('color', models.CharField(max_length=50)),
                ('body_code', models.CharField(max_length=50)),
                ('engin_code', models.CharField(max_length=50)),
                ('characteristics', models.TextField(max_length=1000)),
                ('code1', models.CharField(max_length=50)),
                ('code2', models.CharField(max_length=50)),
                ('code3', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(models.Employee, on_delete=models.CASCADE)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=200)),
                ('car', models.ForeignKey(Car, on_delete=models.CASCADE)),
                ('order_date', models.DateField(auto_now=True)),
                ('sale_date', models.DateField(auto_now=True)),
                ('execution_notes', models.TextField(max_length=1000)),
                ('payment_notes', models.TextField(max_length=1000)),
                ('paied', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(models.Employee, on_delete=models.CASCADE)),
            ],
        ),
    ]
